packages:
  - "."

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - cwebp-bin
  - esbuild
  - mozjpeg
  - pngquant-bin
  - prisma
  - sharp
  - unrs-resolver
